using System.Text.Json.Serialization;

namespace FabCopilot.Contracts.Models;

/// <summary>
/// A predictive alert generated by the Fusion Engine with multi-tier evidence.
/// </summary>
public sealed class PredictiveAlert
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = "";

    [JsonPropertyName("equipment_id")]
    public string EquipmentId { get; set; } = "";

    /// <summary>Alert severity: Info, Warning, Critical.</summary>
    [JsonPropertyName("severity")]
    public AlertSeverity Severity { get; set; }

    /// <summary>Alert title (short description).</summary>
    [JsonPropertyName("title")]
    public string Title { get; set; } = "";

    /// <summary>Detailed alert message.</summary>
    [JsonPropertyName("message")]
    public string Message { get; set; } = "";

    /// <summary>The diagnostic hypothesis that generated this alert.</summary>
    [JsonPropertyName("hypothesis")]
    public DiagnosticHypothesis? Hypothesis { get; set; }

    /// <summary>Recommended actions.</summary>
    [JsonPropertyName("actions")]
    public List<string> Actions { get; set; } = [];

    /// <summary>Manual references.</summary>
    [JsonPropertyName("manual_references")]
    public List<string> ManualReferences { get; set; } = [];

    /// <summary>When the alert was generated.</summary>
    [JsonPropertyName("generated_at")]
    public DateTimeOffset GeneratedAt { get; set; } = DateTimeOffset.UtcNow;

    /// <summary>Whether this alert has been acknowledged.</summary>
    [JsonPropertyName("acknowledged")]
    public bool Acknowledged { get; set; }

    /// <summary>Who acknowledged it.</summary>
    [JsonPropertyName("acknowledged_by")]
    public string? AcknowledgedBy { get; set; }

    [JsonPropertyName("acknowledged_at")]
    public DateTimeOffset? AcknowledgedAt { get; set; }
}

/// <summary>
/// Alert severity levels.
/// </summary>
public enum AlertSeverity
{
    Info = 0,
    Warning = 1,
    Critical = 2
}
